version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli
      
  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - cd glue/jobs
      - echo "Preparing Glue job scripts..."
      
  build:
    commands:
      - echo "Build phase started on $(date)"
      - |
        # Upload Glue job script to S3
        aws s3 cp stream_processor.py s3://ecommerce-streaming-dev-scripts-881786084229/glue-jobs/stream_processor.py
      - echo "Glue job script uploaded to S3"
      - echo "Script will be used on next Glue job run"
      
  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      - echo "Deployment completed successfully"
      - echo "The updated script is now in S3 and will be used when the Glue job runs"
      - echo "Build completed on $(date)"

artifacts:
  files:
    - stream_processor.py
  name: glue-job-$(date +%Y%m%d-%H%M%S)