version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli
      
  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - cd glue/jobs
      - echo "Preparing Glue job scripts..."
      
  build:
    commands:
      - echo "Build phase started on $(date)"
      - |
        # Upload Glue job script to S3
        aws s3 cp stream_processor.py s3://ecommerce-streaming-dev-scripts-881786084229/glue-jobs/stream_processor.py
      - echo "Glue job script uploaded to S3"
      
  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      - |
        # Get the current Glue job details to extract the role
        GLUE_ROLE=$(aws glue get-job \
          --job-name ecommerce-streaming-dev-stream-processor \
          --region ${AWS_REGION} \
          --query 'Job.Role' \
          --output text)
        
        echo "Using Glue role: $GLUE_ROLE"
        
        # Update Glue job with new script
        aws glue update-job \
          --job-name ecommerce-streaming-dev-stream-processor \
          --job-update "Role=${GLUE_ROLE},Command={Name=glueetl,ScriptLocation=s3://ecommerce-streaming-dev-scripts-881786084229/glue-jobs/stream_processor.py,PythonVersion=3}" \
          --region ${AWS_REGION}
      - echo "Glue job updated successfully"
      - echo "Build completed on $(date)"

artifacts:
  files:
    - stream_processor.py
  name: glue-job-$(date +%Y%m%d-%H%M%S)